Readme: add specific binary name a user should use
ARMmbed/mbed-os-example-bootloader-blinky pull request #6
Opened 2017-03-23 10:19 UTC by 0xc0170

@c1728p9  @ashok-rao Please review

2017-03-23 11:45 UTC, ashok-rao commented on README.md
> +1. Create a bootloader for your board in the project [mbed-os-example-bootloader](https://github.com/ARMmbed/mbed-os-example-bootloader). The bootloader imagine is named ``mbed-os-example-bootloader.
typo: imagine -> "image".

2017-03-23 11:46 UTC, ashok-rao commented on README.md
>      "target_overrides": {
Are we planning to remove "NUCLEO_F429ZI" hard code and generalize it more to say something like <your_bootloader_here>.img or similar ??

2017-03-23 11:48 UTC, ashok-rao requested changes
Requesting minor changes. Also, @c1728p9 ..any plans to add more details to the troubleshooting section? (say) where to find the right "restrict_size", how to check VTOR for any changes due to flash algo etc?

2017-03-23 11:50 UTC, 0xc0170 commented on README.md
>      "target_overrides": {
Can you pinpoint what lines should be changed and how? To propose changes here? the readme shows how to do it for one target (easy to replace the target name).

2017-03-23 11:50 UTC, ashok-rao commented
We also need to add links to the FLASH IAP, flash porting guide & the bootloader docs..

2017-03-23 11:53 UTC, 0xc0170 commented
Rebased . I added link to the bootloader tutorial. That tutorial can be the entry point for bootloader (and we add links for flash IAP, etc) there - a meeting point. does that sound good?

2017-03-23 12:05 UTC, ashok-rao commented on README.md
>      "target_overrides": {
Current: "NUCLEO_F429ZI": {
                       "target.bootloader_img": "bootloader/NUCLEO_F429ZI.bin"

Proposed: In mbed_app.json, to add your newly built bootloader image to the application, make the following changes:
"<target_name>": {
   "target.bootloader_img": "bootloader\<Your_new_bootloader_filename).img

Something like this?? Just to keep it more generic.. else in the future we will have a phase similar to the era of K64F .. but for the NUCLEO_F429ZI this time.. what do you think?

2017-03-23 12:18 UTC, 0xc0170 commented on README.md
>      "target_overrides": {
Fixed now

2017-03-23 14:23 UTC, ashok-rao commented
Ok. just pending the troubleshooting section now..

2017-03-23 14:57 UTC, 0xc0170 commented
>Ok. just the troubleshooting section pending now..

This section is part of the bootloader tutorial. That page plus related pages (flash IAP, etc) should cover it all (if not , lets fix it there).

2017-03-23 16:13 UTC, ashok-rao commented
you mean to say https://docs.mbed.com/docs/mbed-os-handbook/en/latest/advanced/bootloader/ is where the troubleshooting section needs to go?

2017-03-23 16:24 UTC, 0xc0170 commented
> you mean to say https://docs.mbed.com/docs/mbed-os-handbook/en/latest/advanced/bootloader/ is where the troubleshooting section needs to go? .. If yes, then fine with me. Let's add more to the docs there rather than overpopulating the readme.

Yes, exactly, so any readme can point there to have it in one place. I'll add it tomorrow

2017-03-24 10:06 UTC, 0xc0170 commented
Requested changes - done - is that correct?

2017-03-24 10:09 UTC, ashok-rao commented
I don't see the troubleshooting section on the bootloader docs page yet.. can you point me to a link if I'm looking in the wrong place?

2017-03-24 10:17 UTC, ashok-rao commented
As discussed, these links and other sections will go into "bootloader tutorial" page.. This PR is good to go! :-)

2017-03-24 10:17 UTC, ashok-rao approved these changes

2017-03-24 10:20 UTC, merged